apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-counter
  labels:
    app.kubernetes.io/name: app
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: app
        spec:
          containers:
          - name: hello
            image: cmd.cat/curl
            args:
            - curl
            - -XPOST
            - python-service/api/v1/info
          restartPolicy: Never
